-- ============================================
-- Crypto Trader - Database Schema
-- ============================================

-- Signals: Every signal generated by the strategy engine
CREATE TABLE IF NOT EXISTS signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('LONG', 'SHORT', 'NEUTRAL')),
  strength TEXT NOT NULL CHECK (strength IN ('weak', 'moderate', 'strong')),
  entry_price NUMERIC NOT NULL,
  stop_loss NUMERIC NOT NULL,
  take_profit NUMERIC NOT NULL,
  risk_reward_ratio NUMERIC NOT NULL,
  reason TEXT NOT NULL,
  indicators JSONB NOT NULL,
  regime JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- LLM Decisions: Every LLM filter decision
CREATE TABLE IF NOT EXISTS llm_decisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  signal_id UUID REFERENCES signals(id),
  decision TEXT NOT NULL CHECK (decision IN ('APPROVE', 'REJECT', 'DELAY')),
  confidence NUMERIC NOT NULL,
  reasoning TEXT NOT NULL,
  delay_minutes INTEGER,
  news_context JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Trades: Every executed (simulated) trade
CREATE TABLE IF NOT EXISTS trades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('LONG', 'SHORT')),
  entry_price NUMERIC NOT NULL,
  exit_price NUMERIC,
  quantity NUMERIC NOT NULL,
  entry_time TIMESTAMPTZ NOT NULL,
  exit_time TIMESTAMPTZ,
  pnl NUMERIC,
  pnl_percent NUMERIC,
  commission NUMERIC DEFAULT 0,
  outcome TEXT CHECK (outcome IN ('win', 'loss', 'breakeven')),
  exit_reason TEXT CHECK (exit_reason IN ('take_profit', 'stop_loss', 'trailing_stop', 'structure_break', 'manual', 'regime_change')),
  signal_id UUID REFERENCES signals(id),
  llm_decision_id UUID REFERENCES llm_decisions(id),
  post_trade_analysis TEXT,
  is_open BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Regime Log: Market regime snapshots
CREATE TABLE IF NOT EXISTS regime_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol TEXT NOT NULL,
  volatility TEXT NOT NULL,
  trend TEXT NOT NULL,
  decision TEXT NOT NULL,
  fear_greed_index INTEGER,
  fear_greed_label TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Portfolio Snapshots: Periodic portfolio state
CREATE TABLE IF NOT EXISTS portfolio_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  total_equity NUMERIC NOT NULL,
  available_cash NUMERIC NOT NULL,
  positions JSONB,
  total_pnl NUMERIC,
  total_pnl_percent NUMERIC,
  total_trades INTEGER DEFAULT 0,
  win_rate NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_created ON signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_is_open ON trades(is_open);
CREATE INDEX IF NOT EXISTS idx_trades_created ON trades(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_regime_log_symbol ON regime_log(symbol);
CREATE INDEX IF NOT EXISTS idx_regime_log_created ON regime_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_created ON portfolio_snapshots(created_at DESC);
